### ISSUE TITLE
Exception in RadialGradientPaint

### ISSUE THREAD

**Issue by istinnstudio** [rototor/pdfbox-graphics2d#48]
```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class [D cannot be cast to class [F ([D and [F are in module java.base of loader 'bootstrap')
	at de.rototor.pdfbox.graphics2d.PdfBoxGraphics2DPaintApplier.buildRadialGradientShading(PdfBoxGraphics2DPaintApplier.java:791)
	at de.rototor.pdfbox.graphics2d.PdfBoxGraphics2DPaintApplier.applyPaint(PdfBoxGraphics2DPaintApplier.java:289)
	at de.rototor.pdfbox.graphics2d.PdfBoxGraphics2DPaintApplier.applyPaint(PdfBoxGraphics2DPaintApplier.java:214)
	at de.rototor.pdfbox.graphics2d.PdfBoxGraphics2D.applyPaint(PdfBoxGraphics2D.java:1065)
	at de.rototor.pdfbox.graphics2d.PdfBoxGraphics2D.applyPaint(PdfBoxGraphics2D.java:1031)
	at de.rototor.pdfbox.graphics2d.PdfBoxGraphics2D.fill(PdfBoxGraphics2D.java:931)
```

**Comment by rototor** [comment]
Would you mind giving some context? What are you doing? Can you provide a minimal reproducing sample?

Are you rendering a SVG or are you using another library to perform drawings? What version of PDFBoxGraphics2D are you using?

**Comment by istinnstudio** [comment]
the latest github version, build in maven, some complex drawings in Graphics2D, no SVG conversion. It is very difficult to constract a a minimal reproducing sample unfortunatelly but I will give some info.   I have just used the example @ readme to send my generated drawing to pdf-graphics2d instead of Batik SVGGraphics2D (generator), without having much knowledge of whats going on. Batik PDF transcoder generate huge pdf files if there are gradients, so I ve tried pdf-graphics2d to see the result compare differences etc.  Graphics2D code without the RadialGradientPaint (only Color fills) renders OK with  pdf-graphics2d.
 an other error is this ( only if  dispose is used ) :
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Internal save/restore state error. Should never happen.
	at de.rototor.pdfbox.graphics2d.PdfBoxGraphics2D.contentStreamRestoreState(PdfBoxGraphics2D.java:826)
	at de.rototor.pdfbox.graphics2d.PdfBoxGraphics2D.dispose(PdfBoxGraphics2D.java:433)
